<a href="https://colab.research.google.com/github/harada26009/TU_M_Math/blob/main/Chap02_Ex-05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
from ast import increment_lineno
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

#可視化ライブラリ
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

#小数第３位まで表示
%precision 3

'%.3f'

In [15]:
import scipy.linalg as linalg

a = np.array([[1,2,3],[1,3,2],[3,1,2]])

#逆行列
print("逆行列")
print(linalg.inv(a))

#固有値と固有値ベクトル
eig_value,eig_vector =linalg.eig(a)

print("固有値")
print(eig_value)
print("固有ベクトル")
print(eig_vector)



逆行列
[[-0.333  0.083  0.417]
 [-0.333  0.583 -0.083]
 [ 0.667 -0.417 -0.083]]
固有値
[ 6.   +0.j -1.414+0.j  1.414+0.j]
固有ベクトル
[[-0.577 -0.722  0.16 ]
 [-0.577 -0.143 -0.811]
 [-0.577  0.677  0.563]]
