<a href="https://colab.research.google.com/github/harada26009/TU_M_Math/blob/main/Chap05_Ex5-2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
from ast import increment_lineno
import numpy as np
import numpy.random as random
import scipy as sp

import matplotlib.pyplot as plot
import matplotlib as mpl
%matplotlib inline

%precision 3

'%.3f'

練習問題5-2

In [67]:
sample_names = np.array(['a','b','c','d','a'])
random.seed(0)
data = random.randn(5,5)

print(data[sample_names != 'c'])

[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]
