<a href="https://colab.research.google.com/github/harada26009/TU_M_Math/blob/main/Chap02_Ex-03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from ast import increment_lineno
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series, DataFrame

#可視化ライブラリ
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

#小数第３位まで表示
%precision 3

'%.3f'

In [7]:
m = np.ones((5,5),dtype='i')*3
print(m.dot(m))

[[45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]]
