<a href="https://colab.research.google.com/github/harada26009/TU_M_Math/blob/main/Chap05_Cm5-2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from ast import increment_lineno
import numpy as np
import numpy.random as random
import scipy as sp

import matplotlib.pyplot as plot
import matplotlib as mpl
%matplotlib inline

%precision 3

'%.3f'

In [8]:
A = np.array([[5,1,0,1],
              [1,9,-5,7],
              [0,-5,8,-3],
              [1,7,-3,10]])
b = np.array([2,10,5,10])

In [9]:
L = sp.linalg.cholesky(A)

t = sp.linalg.solve(L.T.conj(),b)
x = sp.linalg.solve(L,t)

print(x)

[-0.051  2.157  2.01   0.098]


In [10]:
np.dot(A,x)

array([ 2., 10.,  5., 10.])

In [11]:
L = np.linalg.cholesky(A)

t = np.linalg.solve(L,b)
x = np.linalg.solve(L.T.conj(),t)

print(x)

[-0.051  2.157  2.01   0.098]


In [12]:
np.dot(A,x)

array([ 2., 10.,  5., 10.])

In [14]:
from scipy import integrate
import math
import numpy as np

integrate.dblquad(lambda y, x: 1/(np.sqrt(x+y)*(1+x+y)**2), 0, 1, lambda x: 0, lambda x: 1-x)

(0.285, 0.000)