<a href="https://colab.research.google.com/github/harada26009/TU_M_Math/blob/main/Chap05_Ex5-6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
from ast import increment_lineno
import numpy as np
import numpy.random as random
import scipy as sp

import matplotlib.pyplot as plot
import matplotlib as mpl
%matplotlib inline

%precision 3

'%.3f'

練習問題5-4

In [70]:
sample_multi_array_data2 = np.arange(16).reshape(4,4)
sample_multi_array_data2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [72]:
print(np.sqrt(sample_multi_array_data2))

[[0.    1.    1.414 1.732]
 [2.    2.236 2.449 2.646]
 [2.828 3.    3.162 3.317]
 [3.464 3.606 3.742 3.873]]


In [75]:
print('最大値：',sample_multi_array_data2.max())
print('最小値：',sample_multi_array_data2.min())
print('合計値：',sample_multi_array_data2.sum())
print('平均値：',sample_multi_array_data2.mean())

最大値： 15
最小値： 0
合計値： 120
平均値： 7.5


In [76]:
print('対角成分の和：',np.trace(sample_multi_array_data2))

対角成分の和： 30
