<a href="https://colab.research.google.com/github/harada26009/TU_M_Math/blob/main/Chap05_Ex5-9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
from ast import increment_lineno
import numpy as np
import numpy.random as random
import scipy as sp

import matplotlib.pyplot as plot
import matplotlib as mpl
%matplotlib inline

%precision 3

'%.3f'

練習問題5-7

In [78]:
sample_array1 = np.arange(12).reshape(3,4)
sample_array2 = np.arange(12).reshape(3,4)
np.concatenate([sample_array1,sample_array2],axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

練習問題5-8

In [79]:
np.concatenate([sample_array1,sample_array2],axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

練習問題5-9

In [84]:
sample_list = [1,2,3,4,5]
np.array(sample_list) + 3

array([4, 5, 6, 7, 8])