<a href="https://colab.research.google.com/github/harada26009/TU_M_Math/blob/main/Chap05_Cm5-3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
from ast import increment_lineno
import numpy as np
import numpy.random as random
import scipy as sp

import matplotlib.pyplot as plot
import matplotlib as mpl
%matplotlib inline

%precision 3

'%.3f'

In [23]:
A = np.array([[5,1,0,1],
              [1,9,-5,7],
              [0,-5,8,-3],
              [1,7,-3,10]])
b = np.array([2,10,5,10])

In [24]:
L = sp.linalg.cholesky(A)

t = sp.linalg.solve(L.T.conj(),b)
x = sp.linalg.solve(L,t)

print(x)

[-0.051  2.157  2.01   0.098]


In [25]:
np.dot(A,x)

array([ 2., 10.,  5., 10.])

In [26]:
L = np.linalg.cholesky(A)

t = np.linalg.solve(L,b)
x = np.linalg.solve(L.T.conj(),t)

print(x)

[-0.051  2.157  2.01   0.098]


In [27]:
np.dot(A,x)

array([ 2., 10.,  5., 10.])

In [28]:
from scipy import integrate
import math
import numpy as np

integrate.dblquad(lambda y, x: 1/(np.sqrt(x+y)*(1+x+y)**2), 0, 1, lambda x: 0, lambda x: 1-x)

(0.285, 0.000)

In [29]:
from scipy.optimize import minimize
def func(x):
  return x ** 2 + 1

def cons(x):
  return(x + 1)

cons = (
    {'type': 'ineq', 'fun': cons}
)
x = -10
result = minimize(func, x0=x, constraints=cons,method='SLSQP')
print(result)

     message: Optimization terminated successfully
     success: True
      status: 0
         fun: 1.0
           x: [ 0.000e+00]
         nit: 2
         jac: [ 1.490e-08]
        nfev: 5
        njev: 2
 multipliers: [ 0.000e+00]


In [30]:
print('Y:',result.fun)
print('X',result.x)

Y: 1.0
X [0.]
